"""empty message

Revision ID: 86516f94cafa
Revises: b7ade2d8abbe
Create Date: 2022-08-15 16:42:49.635742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86516f94cafa'
down_revision = 'b7ade2d8abbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
